[31m1 error occurred:
	* failed to catalog: unable to load image: unable to use DockerDaemon source: pull failed: Error response from daemon: Head "https://cgr.dev/v2/chainguard/grafana/manifests/latest": unknown: Forbidden[0m
